import { Task } from './core/models/task';
const tasksString = JSON.stringify([
  {
    id: 60,
    title: 'task 60',
    description: '4 JIRA clone application to manage all task in easy way.',
    status: 'TODO',
    priority: 'LOW',
    createdAt: 'Tue, 27 Dec 2022 00:09:15',
    completedAt: null,
  },
  {
    id: 58,
    title: 'Manager RB App 58',
    description: 'JIRA clone application to manage all task in easy way.',
    status: 'TODO',
    priority: 'MEDIUM',
    createdAt: 'Tue, 27 Dec 2022 00:06:13',
    completedAt: null,
  },
  {
    id: 57,
    title: 'Manager RB App 57',
    description: 'JIRA clone application to manage all task in easy way.',
    status: 'TODO',
    priority: 'MEDIUM',
    createdAt: 'Tue, 27 Dec 2022 00:06:13',
    completedAt: null,
  },
  {
    id: 56,
    title: 'Manager RB App 56',
    description: 'JIRA clone application to manage all task in easy way.',
    status: 'TODO',
    priority: 'MEDIUM',
    createdAt: 'Tue, 27 Dec 2022 00:06:13',
    completedAt: null,
  },
  {
    id: 55,
    title: 'Manager RB App 55',
    description: 'JIRA clone application to manage all task in easy way.',
    status: 'TODO',
    priority: 'MEDIUM',
    createdAt: 'Tue, 27 Dec 2022 00:06:13',
    completedAt: null,
  },
  {
    id: 5,
    title: 'Manager RB App 5',
    description: 'JIRA clone application to manage all task in easy way.',
    status: 'TODO',
    priority: 'MEDIUM',
    createdAt: 'Tue, 27 Dec 2022 00:06:13',
    completedAt: null,
  },
  {
    id: 51,
    title: 'Manager RB App 51',
    description: 'JIRA clone application to manage all task in easy way.',
    status: 'TODO',
    priority: 'MEDIUM',
    createdAt: 'Tue, 27 Dec 2022 00:06:13',
    completedAt: null,
  },
  {
    id: 25,
    title: 'Manager RB App 25',
    description: 'JIRA clone application to manage all task in easy way.',
    status: 'TODO',
    priority: 'MEDIUM',
    createdAt: 'Tue, 27 Dec 2022 00:06:13',
    completedAt: null,
  },
  {
    id: 26,
    title: 'Manager RB App 26',
    description: 'JIRA clone application to manage all task in easy way.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    createdAt: 'Tue, 27 Dec 2022 00:06:13',
    completedAt: null,
  },
]);
const TASKS: Task[] = JSON.parse(tasksString);
export default TASKS;
